--- #YAML:1.0
name:               CPAN-Mini-Visit-Simple
version:            0.003
abstract:           Lightweight traversal of a minicpan repository
author:
    - James E Keenan (jkeenan@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Path:         2.06
    IO::CaptureOutput:  0
    Test::Simple:       0.44
requires:
    CPAN::Mini:    0
    File::Find:    0
    File::Spec:    0
    File::Temp:    0.14
    Path::Class:   0.15
    Scalar::Util:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
